account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from account.views import signup

urlpatterns=[
    url(r'^signup/$',signup,name='signup'),
    url(r'^login/$',auth_views.login,{'template_name':'login.html'},name='login'),
    url(r'^logout/$',auth_views.logout,{'next_page':'home'},name='logout'),
    
]

livewiredemos/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from todo.views import home,todolist

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name='home'),
    url(r'^todos/$',todolist,name='todolist'),
    url(r'^todos/',include('todo.urls',namespace='todo')),
    url(r'^account/',include('account.urls')),
    
]

todo/urls.py
from django.conf.urls import url
from todo.views import todoadd,todoedit,tododelete,todolist


urlpatterns = [
    url(r'^$',todolist,name='todolist'),
    url(r'^add/$',todoadd,name='todoadd'),
    url(r'^edit/(?P<pk>\d+)$',todoedit,name='todoedit'),
    url(r'^delete/(?P<pk>\d+)$',tododelete,name='tododelete'),
    ]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here
class Todo(models.Model):
    """ todo todos table in db"""
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
   
    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from todo.models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model=Todo
        fields={'title','description'}

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
# Create your views here.
def signup(request):
    signupform=UserCreationForm(request.POST or None)
    if signupform.is_valid():
        signupform.save()
        username=signupform.cleaned_data.get('username')
        raw_password=signupform.cleaned_data.get('password1')
        user=authenticate(username=username,password=raw_password)
        login(request,user)
        return redirect('todolist')

    return render(request,'signup.html',{'form':signupform})

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from todo.models import Todo
from todo.forms import TodoForm

# Create your views here.
def home(request):
    return render(request,'home.html')


@login_required
def todolist(request):
    alltodos=Todo.objects.all()
    return render(request,'todolist.html',{'todos':alltodos})

@login_required
def todoadd(request):
    todoform=TodoForm(request.POST or None)
    if todoform.is_valid():
        todoform.save()
        return redirect('todolist')    
    return render(request,'todoadd.html',{'form':todoform})

@login_required
def todoedit(request,pk):
    todo = get_object_or_404(Todo,pk=pk)
    todoform = TodoForm(request.POST or None,instance=todo)
    if todoform.is_valid():
        todoform.save()
        return redirect('todolist')
    return render(request,'todoadd.html',{'form':todoform})
@login_required
def tododelete(request,pk):
    todo = get_object_or_404(Todo,pk=pk)
    if request.method=='POST':
        todo.delete()
        return redirect('todolist')
    return render(request,'tododelete.html',{'todo':todo})

templates/base.html
<html>
	
<head>
    
		<title>{% block title %}{% endblock %}</title>
    
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrityjksxnsk"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	</head>
	<body>
	{% include 'navbar.html' %}
	{% block content %}{% endblock %}
	</body>
</html>

templates/help.html
{%extends 'base.html'%}

{%block title%}Todo{%endblock%}

{% block content%}
<body>
<p>
If you need some datas,you can contact us.
</p>


</body>

{%endblock%}

templates/home.html
{% extends 'base.html'%}

{%block title%}Home page{%endblock%}

{% block content%}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<head>
<style>
.mySlides {display:none;}
.ff{
max-width:100%;
margin-top: 14px!important;
}
@media only screen and (max-width: 600px) {
.ff{
max-width:100%;
margin-top: 10px!important;
margin-top:51px;
margin-left:-141px;
width:100%;
height:auto;
}}
@media only screen and (max-width: 600px) {
.gg{
margin-top:58px;
margin-left:139px;
width:100%;
height:auto;
}
}

.demo3{
font-size:20px;
font-family:Arial, Helvetica, sans-serif;
font-weight:400;
}

.test1{
    margin-left: 738px;
	font-size:18px;
	}
	.test2{
	margin-right: 288px;
	font-size:18px;
	
	}
	.test3{
	margin-left: -297px;
	font-size:18px;
	}

</style>
</head>

<body>

<div>

{%if user.is_authenticated%}
<h4>Hi,{{user.username}}!!!Welcome<a href="{%url 'logout' %}">Logout</a></h4>

{%endif%}
</div>

<span class="demo3" style="color:#FF6600"><marquee>Welcome to livewire</marquee></span>

<div class="ff" >
                   
				   
				   
			 <img class="mySlides gg" src="https://support.livewireindia.com/sites/default/files/styles/original/public/banner_7.jpg?itok=4DAmrA08" width="100%" height="auto" >
				   
				   
			<img class="mySlides gg" src="https://support.livewireindia.com/sites/default/files/styles/original/public/banner_6.jpg?itok=lhEJqaNv" width="100%" height="auto">
							 
			 <img class="mySlides gg" src="https://support.livewireindia.com/sites/default/files/styles/original/public/CSR_banner.jpg?itok=c2RjgWae" width="100%" height="auto">   
						   
						   
</div>




<br /><br />
<p align="center" style="font-family:Arial, Helvetica, sans-serif; font-size:16px">Education is any kind of knowledge transitioned into learning.<br />

LIVEWIRE promote niche training in IT, Electronics & Electricals creating experts for emerging technology industries and specialist technology jobs. A part of CADD Centre, which is Asia's largest CAD/CAM/CAE training institute. LIVEWIRE is present in 100 locations across India and 6 Countries.</p>
<br /><br />


<div>
<div style="width: 100%"><iframe width="100%" height="600" src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=livewire%2Cmylapore%2Ctamil%20nadu+(django%20project)&ie=UTF8&t=&z=14&iwloc=B&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"><a href="https://www.mapsdirections.info/en/journey-planner.htm">Route Finder</a></iframe></div><br />

</div>

<div>
<nav class="navbar navbar-dark bg-dark" style="font-size: 14px;font-family: serif;    height: 70px;background-color: #73dada!important;">

<a class="navbar-brand test1 " href="{% url 'home' %}" style="color: #000000">Help </a>
<a class="navbar-brand  test2" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-phone"></i>&nbsp;&nbsp;90876543218 </a>
<a class="navbar-brand  test3" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-envelope"></i>&nbsp;&nbsp;livewireindia@gmail.com </a>
</div>


 <script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 4000); // Change image every 2 seconds
}
</script>

</body>

{%endblock%}

templates/login.html
{%extends 'base.html'%}
{%block title%}Login{%endblock%}

{%block content%}
<head>
<style>
.test1{
    margin-left: 738px;
	font-size:18px;
	}
	.test2{
	margin-right: 288px;
	font-size:18px;
	
	}
	.test3{
	margin-left: -297px;
	font-size:18px;
	}
</style>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body style="background-color: aquamarine;">
<br /><br />
<h3 align="center" style="color:#FF9999">Login</h3>
<br />
<form method="POST" style="margin-left:570px">
{%csrf_token%}
{{form.as_p}}

<input style="background-color:#FF3333; color:#fff; width:88px" type="submit" name="login" value="Login" />&nbsp;&nbsp;&nbsp;&nbsp;
                  <span><a href="http://127.0.0.1:8000/account/signup/">Signup here</a></span>
</form>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

<div>
<nav class="navbar navbar-dark bg-dark" style="font-size: 14px;font-family: serif;    height: 70px;background-color: #73dada!important;">

<a class="navbar-brand test1 " href="{% url 'home' %}" style="color: #000000">Help </a>
<a class="navbar-brand  test2" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-phone"></i>&nbsp;&nbsp;90876543218 </a>
<a class="navbar-brand  test3" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-envelope"></i>&nbsp;&nbsp;livewireindia@gmail.com </a>
</div>
</body>

{%endblock%}

templates/logout.html
{%extends 'base.html'%}
{%block title%}Logout{%endblock%}
{%block content%}

You have successfully logged out!!

{%endblock%}

templates/navbar.html
<head>
<style>
.demo{
    margin-left: -907px;
    
}
.demo1{
margin-left:-903px;
   
}
.demo3{
margin-left: -156px;
    height: 68px;
    width: 200px;
    margin-top: -24px;
	
}

</style>

</head>


<nav class="navbar navbar-dark bg-dark" style="font-size: 14px;font-family: serif;    height: 70px; background-color: #010d38!important;">
  <a class="navbar-brand demo2" href="{% url 'home' %}" style="    color: #ffd745;">Home</a>
  
  <a class="navbar-brand demo" href="http://127.0.0.1:8000/todos/" style="    color: #ffd745;" >All Todos</a>
  
  <a class="navbar-brand demo1" href="http://127.0.0.1:8000/todos/add/" style="    color: #ffd745;">Add Todo</a>
  
  <a class="navbar-brand demo1" href="http://127.0.0.1:8000/account/signup/" style="    color: #ffd745;margin-left: -904px;">Signup</a>
  
  <a class="navbar-brand demo1" href="http://127.0.0.1:8000/account/login/" style="    color: #ffd745;">Login</a>
  
  
  
  
  <a href="http://127.0.0.1:8000/">
    <span class="navbar-toggler-icon"><img class="demo3" src="https://support.livewireindia.com/tmp/images/live_wire_logo.jpg" alt="livewire logo" /></span>
  </a>
  <div class="collapse navbar-collapse" id="navbarNav">
    
  </div>
</nav>

templates/signup.html
{%extends 'base.html'%}

{%block title%}{%endblock%}

{%block content%}
<head>
<style>
.test1{
    margin-left: 738px;
	font-size:18px;
	}
	.test2{
	margin-right: 288px;
	font-size:18px;
	
	}
	.test3{
	margin-left: -297px;
	font-size:18px;
	}
</style>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body style="background-color: aquamarine">
<br /><br />

<h3 align="center" style="color:#e43acf">Registration form</h3>
<br />
<form method="post" style="margin-left:370px">
{%csrf_token%}

{{form.as_p}}


<input style="background-color:#FFCC33; color:#000033; width:100px" type='submit' name='signup' value="Sign up" />


</form>


</body>

<br /><br /><br /><br /><br /><br />

<div>
<nav class="navbar navbar-dark bg-dark" style="font-size: 14px;font-family: serif;    height: 70px;background-color: #73dada!important;">

<a class="navbar-brand test1 " href="{% url 'home' %}" style="color: #000000">Help </a>
<a class="navbar-brand  test2" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-phone"></i>&nbsp;&nbsp;90876543218 </a>
<a class="navbar-brand  test3" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-envelope"></i>&nbsp;&nbsp;livewireindia@gmail.com </a>
</div>

{%endblock%}

templates/todoadd.html
{%extends 'base.html'%}

{%block title%}Todo{%endblock%}

{%block content%}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<head>
<style>

.test1{
    margin-left: 738px;
	font-size:18px;
	}
	.test2{
	margin-right: 288px;
	font-size:18px;
	
	}
	.test3{
	margin-left: -297px;
	font-size:18px;
	}
	</style>
</head>
<body style="background-color: #66ffcc38;">
<h3 align="center" style=" color:#FF99CC">Add Data</h3>

<form method="post" style="padding-left:500px">
{%csrf_token%}

 {{form.as_p}}
 
 <input style="background-color: #FF3333; color:#FFFFFF" type="submit" name ="savetodo" value ="Save Todo">
 
 </form>
 
 <br />
 <br />
 <p align="center">Add todo page as two fields, one is title and another is description</p>
 <br /><br /><br /><br />
 <div>
<nav class="navbar navbar-dark bg-dark" style="font-size: 14px;font-family: serif;    height: 70px;background-color: #73dada!important;">

<a class="navbar-brand test1 " href="http://127.0.0.1:8000/todos/help/" style="color: #000000">Help </a>
<a class="navbar-brand  test2" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-phone"></i>&nbsp;&nbsp;90876543218 </a>
<a class="navbar-brand  test3" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-envelope"></i>&nbsp;&nbsp;livewireindia@gmail.com </a>
</div>
 </body>
 
 {%endblock%}
 

templates/tododelete.html
{%extends 'base.html'%}

{%block title%}Delete Todo{%endblock%}

{%block content%}

<form method="post">
{%csrf_token%}

<h1 align="center">Are you sure ?</h1>

<p align="center">Are you sure you want to delete the selected one&nbsp;&nbsp;"{{todo.title}}?"</p>
<input style="margin-left:580px;     color: #f91010;" type="submit" name="tododelete" value="YES, i'm sure ">
<a href="http://127.0.0.1:8000/todos/">No, take me back</a>

</form>

{%endblock%}

templates/todolist.html
{%extends 'base.html'%}

{%block title%}All Todos{%endblock%}

{% block content %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<head>

<style>
table,td,th{
border:2px solid  #FF6699;
}

table{
border-collapse:collapse;
width:80%;
}

th{
height:60px;
}

.test1{
    margin-left: 738px;
	font-size:18px;
	}
	.test2{
	margin-right: 288px;
	font-size:18px;
	
	}
	.test3{
	margin-left: -297px;
	font-size:18px;
	}



</style>


</head>
<body style="    background-color: #66ffcc38;">
<div>

{%if user.is_authenticated%}
<h4>Hi,{{user.username}}!!!Welcome<a href="{%url 'logout' %}">Logout</a></h4>

{%endif%}
</div>
<h3 align="center" style="color:#FF3300">All Todos</h3>
<table align="center">
  <thead>
         
		 
		 <tr>
	      <th>Title</th>
		  <th>Description</th>
		   <th>Created at</th>
		    <th>Updated at</th>
			<th>Edit / Delete</th>
			</tr>
			
			</thead>
			
			<tbody>
			
			   {%for todo in todos%}
			   
			    <tr>
				   <td>{{todo.title}}</td>
				   
				   <td>{{todo.description}}</td>
				   
				   <td>{{todo.created_at}}</td>
				   
				   <td>{{todo.updated_at}}</td>
				   
				   
				   
				   <td><a href="{%url 'todo:todoedit' todo.id%}">
				   <button style="color: #74f95c;background-color: #e64891;width: 58px;height: 34px;border-bottom-color: #214a3c;">Edit</button>
				   
				 </a>
				 
				 <a href="{%url 'todo:tododelete' todo.id%} ">
				 <button style="color: #FFFFFF;background-color: #FF0000;width: 58px;height: 34px;border-bottom-color: #214a3c;">Delete</button>
				 </a>
				 </td>
				 				   
				   </tr>
				   
				   {%endfor%}
				   
				   </tbody>
				   
				   

</table>
<br />

    <p align="center" style="font-size:18px">Note: This page contain the list of todo table, here you can find the datas what are you have saved and also you can view when the data is edited and updated,,if needed you can also edit the field and delete it..</p>
	
	<br /><br /><br /><br />
	
	<div>
<nav class="navbar navbar-dark bg-dark" style="font-size: 14px;font-family: serif;    height: 70px;background-color: #73dada!important;">

<a class="navbar-brand test1 " href="{% url 'home' %}" style="color: #000000">Help </a>
<a class="navbar-brand  test2" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-phone"></i>&nbsp;&nbsp;90876543218 </a>
<a class="navbar-brand  test3" href="{% url 'home' %}" style="color: #000000"><i class="fa fa-envelope"></i>&nbsp;&nbsp;livewireindia@gmail.com </a>
</div>
</body>
{%endblock%}